database:
  driver: "ODBC Driver 17 for SQL Server"
  server: "${DB_SERVER}" 
  database: "master"
  trusted_connection: "yes"

source_settings:
  input_file: "ems.csv"
  batch_size: 5000

paths:
  landing_zone: "./data/"
  archive_zone: "./data/archive/"
  error_zone: "./data/error/"